repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        types: [markdown]
        exclude: themes/
      - id: trailing-whitespace
        types: [markdown]
        exclude: themes/
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
        types: [markdown]
        exclude: themes/
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.33.0
    hooks:
      - id: markdownlint-fix
        types: [markdown]
        exclude: themes/
  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.11.2
    hooks:
      - id: markdown-link-check
        args: [ '-c .link-check-config.json' ]
        exclude: ^themes/
